### ISSUE TITLE
build.rst has inarrcute info if building on ubuntu

### ISSUE THREAD

**Issue by cyian-1756** [stelic/limitload#7]
build.rst says to patch panda3d using `patch -p1 <game_directory>/util/patch-panda3d/<name>.patch`. This hangs on Ubuntu as patch expects to read the patch file from stdin.

 `patch -p1 -i <game_directory>/util/patch-panda3d/<name>.patch` would work on Ubuntu

**Comment by nikolmiv** [comment]
Hey, thanks for the report! Added the missing -i option in a96cef1.
